name: Java CI

on:
  push:
    branches:
      - main
      - test-branch-CI
  pull_request:
    branches:
      - main
      - test-branch-CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build com Maven sem rodar testes
      run: mvn clean install -DskipTests
